## **Linear Algebra** ##

**Given the following matrices**

``` 
A = [2  -1] 
    [0   3]
```


``` 
B = [1    4]
    [-2    5]
```

```
scalars - (c = 2, d = 3)
```



**A. Compute the following**
- c(A)
- d(B)
- (c + d)A 
                  


In [16]:
# impporting libraries
import numpy as np

# A and B arrays
A = np.array([[2, -1], [0,  3]])
B = np.array([[1,  4], [-2, 5]])

#  c,d as scalars
c= 2
d= 3
# computing the scalar multiplication
scalar_multiplication_one = c * A
scalar_multiplication_two = d * B
scalar_addition = (c + d) * A

print("Question A\n")
print(f"Result c(A)=\n {scalar_multiplication_one}\n")
print(f"Result d(B)=\n {scalar_multiplication_two}\n")
print(f"Result (c + d)A=\n {scalar_addition}\n")



Question A

Result c(A)=
 [[ 4 -2]
 [ 0  6]]

Result d(B)=
 [[ 3 12]
 [-6 15]]

Result (c + d)A=
 [[10 -5]
 [ 0 15]]



**B. Using the scalar_multiplication given , verify the scalar multiplication properties**

- Properties of scalar multiplication
  ```
   - Associativity of Scalar Multiplication:
    ```
         (c.d)A =  c.(dA)

In [ ]:
# Associativity of Scalar Multiplication
# (c.d)A =  c.(dA)
associativity_check1= (c * d) *A 
associativity_check2 = c * (d * A)

print(f"Matrix One =>\n(c.d)A =\n{associativity_check2}\n")
print(f"Matrix Two =>\nc.(dA) =\n{associativity_check2}\n")
print("Associativity of Scalar Multiplication:", np.array_equal(associativity_check1, associativity_check2))

Matrix One =>
(c.d)A =
[[12 -6]
 [ 0 18]]

Matrix Two =>
c.(dA) =
[[12 -6]
 [ 0 18]]

Associativity of Scalar Multiplication: True




- Properties of scalar 
```
  - Distributivity over Matrix Addition:
        c (A + B)=  cA + cB

In [ ]:
distributivity_check1=  c * (A + B)
distributivity_check2 = (c * A) + (c * B)

print(f"Matrix One =>\nc (A + B) =\n{distributivity_check2}\n")
print(f"Matrix Two =>\ncA + cB =\n{distributivity_check2}\n")
print("Distributivity over Matrix Addition:", np.array_equal(distributivity_check1,distributivity_check2))

Matrix One =>
(c.d)A =
[[ 6  6]
 [-4 16]]

Matrix Two =>
c.(dA) =
[[ 6  6]
 [-4 16]]

Distributivity over Matrix Addition: True




- Properties of scalar 
```
  - Distributivity over scalar Addition:
         (c + d)A =  cA + dA

In [ ]:
distributivity_check1=  (c + d) *A
distributivity_check2 = (c * A) + (d * A)

print(f"Matrix One =>\n (c + d)A =\n{distributivity_check2}\n")
print(f"Matrix Two =>\ncA + dA =\n{distributivity_check2}\n")
print("Distributivity over Scalar Addition:", np.array_equal(distributivity_check1,distributivity_check2))

Matrix One =>
 (c + d)A =
[[10 -5]
 [ 0 15]]

Matrix Two =>
cA + dA =
[[10 -5]
 [ 0 15]]

Distributivity over matrix Addition: True


**C. Find the transpose of both matrices**
 ``` 
A = [2  -1]    =>   A^T =  [2    0]
    [0   3]                [-1   3]
```


``` 
B = [1    4]   =>  B^T  =  [1    -2]
    [-2   5]               [4     5]
```






          

In [30]:
# finding the transpose of  A and B arrays
A = np.array([[2, -1], [0,  3]])
B = np.array([[1,  4], [-2, 5]])

print("The transpose of Array A is: \n", A.transpose(),"\n")
print("The transpose of Array B : \n", B.transpose())


The transpose of Array A is: 
 [[ 2  0]
 [-1  3]] 

The transpose of Array B : 
 [[ 1 -2]
 [ 4  5]]


**D. Check if (A) and (B) are invertible by computing their determinants.** 
- If they are invertible,
- find: A ^ - 1 and B ^ - 1

In [ ]:
# finding the determinant of  A and B arrays
A = np.array([[2, -1], [0,  3]])
B = np.array([[1,  4], [-2, 5]])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)


print("The determinant of Array A is: \n", det_A)
print(f"The determinat of Array A is {det_A }, Is invertible: {det_A != 0}\n") 

print("The determinant of Array B : \n", det_B)
print(f"The determinat of Array B is {det_B }, Is invertible: {det_B != 0}\n") 


The determinant of Array A is: 
 6.0
The determinat of Array A is 6.0, Is invertible: True

The determinant of Array B : 
 13.0
The determinat of Array B is 13.0, Is invertible: True



In [ ]:
# finding the inverse of A and B arrays
A = np.array([[2, -1], [0,  3]])
B = np.array([[1,  4], [-2, 5]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)


print("The Inverse of Array A is: \n", A_inv, "\n")
print("The Inverse of Array B is : \n", B_inv, "\n")



The Inverse of Array A is: 
 [[0.5        0.16666667]
 [0.         0.33333333]] 

The Inverse of Array B : 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]] 

