In [1]:
import numpy as np

* Matrix A has 2 rows and 3 columns
* Matrix B on the other hand has 3 rows and 2 columns
* Both (AB) and (BA) are possible since the number of columns is equal to the number of rows in the other matrix.

In [5]:
A = np.array([[2, -1, 3], [0, 4, 1]])
B = np.array([[1,2], [-2, 0], [5, -3]])
print('Multiplication between A and B is given by:')
print(np.matmul(A, B))
print('\n')
print('Multiplication between B and A is given by:')
print(np.matmul(B, A))

Multiplication between A and B is given by:
[[19 -5]
 [-3 -3]]


Multiplication between B and A is given by:
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
