## Question 1

In [2]:
import numpy as np
matrix = np.random.randint(1, 50, size = (6,6))
print('6 x 6 array:\n', matrix )

6 x 6 array:
 [[12 43 17 43 43 48]
 [ 7 28 26 10 44 15]
 [14  9 21 33 26 39]
 [ 6 24  3  6 17 28]
 [15 44 22 29 31 24]
 [26 13 11 28 32 15]]


## Question 2

In [ ]:
print('First 2 rows:\n', matrix[0:2, 0:])
print('\n')
print('Last 3 columns:\n', matrix[0:, -3:])
print('\n')
print('Even numbers:\n', matrix[matrix % 2 == 0])


First 2 rows:
 [[12 43 17 43 43 48]
 [ 7 28 26 10 44 15]]


Last 3 columns:
 [[43 43 48]
 [10 44 15]
 [33 26 39]
 [ 6 17 28]
 [29 31 24]
 [28 32 15]]


Even numbers:



array([12, 48, 28, 26, 10, 44, 14, 26,  6, 24,  6, 28, 44, 22, 24, 26, 28,
       32], dtype=int32)

## Question 3

In [21]:
reshaped_matrix = matrix.reshape(3, 2, 6)
print('Reshaped Matrix:\n', reshaped_matrix)
print('\n')
flattened_matrix = reshaped_matrix.flatten()
print('Flattened Matrix:\n', flattened_matrix)

Reshaped Matrix:
 [[[12 43 17 43 43 48]
  [ 7 28 26 10 44 15]]

 [[14  9 21 33 26 39]
  [ 6 24  3  6 17 28]]

 [[15 44 22 29 31 24]
  [26 13 11 28 32 15]]]


Flattened Matrix:
 [12 43 17 43 43 48  7 28 26 10 44 15 14  9 21 33 26 39  6 24  3  6 17 28
 15 44 22 29 31 24 26 13 11 28 32 15]


## Question 4

In [25]:
id_matrix = np.eye(4)
print('4 x 4 identity matrix\n', id_matrix)

print('\n')
diag_matrix = np.diag(np.arange(10, 50, 10))
print('Diagonal matrix\n', diag_matrix)


4 x 4 identity matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Diagonal matrix
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


## Question 5

In [31]:
matrix1 = np.random.randint(1, 11, size = (3, 4))
matrix2 = np.random.randint(1, 11, size = (4, 3))

print('3 x 4 matrix')
print(matrix1)
print('\n')
print('4 x 3 matrix')
print(matrix2)
print('\n')
print('Matrix1 and Matrix2 multiplication')
print(np.matmul(matrix1, matrix2))

3 x 4 matrix
[[ 1  3  4  5]
 [ 4  1  3  3]
 [ 7 10  3  7]]


4 x 3 matrix
[[9 5 2]
 [4 1 4]
 [1 7 4]
 [1 7 4]]


Matrix1 and Matrix2 multiplication
[[ 30  71  50]
 [ 46  63  36]
 [113 115  94]]


In [ ]:
def array_operation():
    try:
        x = int(input('Enter number of rows here: '))
        y = int(input('Enter number of columns here: '))
        arr = []
        for i in range(x):
            for j in range(y):
                arr.append(int(input(f'Value at row {i} and column {j}')))
        array = np.array(arr).reshape(x, y)
        print('Original array:')
        print(array)

        square_array = np.where(array % 2 == 0, array ** 2, array)
        odd_square_array = np.where(square_array % 2 != 0, -1, square_array)
        return odd_square_array
    except ValueError as e:
        return(e)
    except Exception as e:
        return e

array_operation()

Original array:
[[1 2 3]
 [4 5 6]]


array([[-1,  4, -1],
       [16, -1, 36]])